### PR TITLE
Enable Continuous Integration using Circle CI and disable KVM acceleration

### PR DESCRIPTION
**Pull request by puiterwijk**
This PR will enable CI testing using CircleCI, and disabled KVM acceleration.

The KVM acceleration is unfortunately unavailable inside the container, but it should be fine to disable it anyway.
The script will be slightly slower, but a lot more portable.

### CODE REVIEW

**Comment by puiterwijk** [comment]
For some numbers, I timed the time this script takes with and without acceleration.
With KVM: +- 5 seconds, without: +- 30 - 50 seconds (lot more variety).

**Review by kashyapc — CHANGES_REQUESTED** [review]
You forgot to update the commit message: s/--accelerate/--enable-kvm/

Besides that looks good; thanks!

**Review by kashyapc — APPROVED** [review]
Looks good to my not-too-experienced-CircleCI-eyes.

**Comment by puiterwijk** [comment]
Thanks!

**Pull request merged**
